import { createNewUser, getUser } from '@/services/user';
import Head from 'next/head'
import { useState } from 'react';

const Home = () => {
  const [form, setForm] = useState({});

  const handleChangeInput = (e) => {
    setForm({...form, [e.target.name]: e.target.value});
  };

  const createMessage = (isError, user) => {
    return isError ? 'The user was succesfully created' :
      `Hi! ${user.name} your user was succesfully created`
  };

  const getNewUser = async (idUser) => {
    try {
      const newUser = await getUser(idUser);
      alert(createMessage(false, newUser));
    }
    catch (error) {
      console.error(error.message);
      return alert(createMessage(true, {}));
    }

  };

  const handleRegisterSubmit = async (e) => {
    e.preventDefault();
    try {
      const responseRegister = await createNewUser(form);
      if(responseRegister.status == 200) getNewUser(responseRegister.user.id);
    } catch {
      alert('Something happened, please try again')
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={e => handleRegisterSubmit(e)}>
          <div>
            <label>Your name</label>
            <input name='name' placeholder="John Smith" onChange={e => handleChangeInput(e)} />
          </div>
          <div>
            <label>Your email</label>
            <input name='email' placeholder="your_email@email.com" onChange={e => handleChangeInput(e)} />
          </div>

          <button type='submit'>Register</button>
        </form>
      </main>
    </>
  )
};

export default Home;
